# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000 # You can keep the timeout

development:
  <<: *default
  database: knitting-generator-db-test

test:
  <<: *default
  database: knitting-generator-db-test

production:
  <<: *default
  database: knitting-generator-db-test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>